### ISSUE TITLE
Make socket manager path configurable on connection form

### ISSUE THREAD

**Issue by georgedbarr** [socketio/socket.io-admin-ui#8]
Hello,

Small feature request to make the socket path configurable on the connection form.

At the moment, 'path' option is not being used and so the socket connection path defaults to '/socket.io'. This makes the tool unusable for anyone not using the default path.

I have linked to the line of code where the socket is instantiated:
https://github.com/socketio/socket.io-admin-ui/blob/eab7bfab64db96ad1ba4b6fb2aea5a3293805a7c/ui/src/App.vue#L93

Thank you!

**Comment by varedz** [comment]
+1

**Comment by fahadpf** [comment]
This is really very much needed at this moment. My socket.io server is also sitting behind a reverse proxy with a custom public-facing path. Due to the current implementation logic, I'm unable to connect with my socket instance directly from [AdminUI](https://admin.socket.io) page and I've no choice other than to forking the project and adding this path configuration myself.
Is there any expected date on when can we have this feature patch in the npm package?

**Comment by darrachequesne** [comment]
Added in https://github.com/socketio/socket.io-admin-ui/commit/7ad384dd3485b8500217a489f8a376d2641d81e0, included in version `0.1.2`:

![Screenshot from 2021-06-02 12-02-39](https://user-images.githubusercontent.com/13031701/120461652-775e9800-c39a-11eb-80a3-70021f5f0383.png)
